[build-system]
requires = ["scikit-build-core>=0.10", "nanobind>=2.4", "setuptools-scm>=8"]
build-backend = "scikit_build_core.build"

[project]
name = "PolyScribe"
dynamic = ["version"]
authors = [{name = "DracoRooks"}]
description = "Custom C++20 tokenizer."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 2 - Pre-Alpha",

    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",

    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Linguistic",

    "License :: OSI Approved :: MIT License"
]
keywords = [
    "Tokenizer",
    "Artificial Intelligence",
    "Machine Learning",
    "Tranformer",
    "Dataset",
    "Natural Language Processing",
    "Parsing"
]

[project.urls]
Repository = "https://github.com/DracoRooks/Scribe.git"
Documentation = "https://polyscribe.readthedocs.io/en/latest/"

[tool.scikit-build]
cmake.version = ">=3.28"
cmake.args = ["-D_BUILD_PY_MOD=ON"]
ninja.make-fallback = true
wheel.packages = []
sdist.include = [
    "CMakeLists.txt",
    "src/*",
    "include/*",
    "python/*"
]

[[tool.dynamic-metadata]]
provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]

[tool.scikit-build.cmake.define]
_BUILD_PY_MOD = "ON"

[tool.cibuildwheel]
build-verbosity = 1
skip = ["pp*"]

[tool.cibuildwheel.windows]
archs = ["AMD64"]
